# --- Created by Ebean DDL
# To stop Ebean DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table official_box_score (
  id                        bigint auto_increment not null,
  gameDate                  datetime not null,
  officialLastName          varchar(25) not null,
  officialFirstName         varchar(25) not null,
  seasonType                varchar(7) not null,
  homeTeamAbbr              varchar(3) not null,
  homeConference            varchar(4) not null,
  homeDivision              varchar(9) not null,
  homeResult                varchar(4) not null,
  homeTeamName              varchar(35) not null,
  homePoints                smallint not null,
  homeAssists               smallint not null,
  homeTurnovers             smallint not null,
  homeSteals                smallint not null,
  homeBlocks                smallint not null,
  homePersonalFouls         smallint not null,
  homeFieldGoalAttempts     smallint not null,
  homeFieldGoalMade         smallint not null,
  homeThreePointAttempts    smallint not null,
  homeThreePointMade        smallint not null,
  homeFreeThrowAttempts     smallint not null,
  homeFreeThrowMade         smallint not null,
  homeReboundsOffense       smallint not null,
  homeReboundsDefense       smallint not null,
  homePointsQ1              smallint not null,
  homePointsQ2              smallint not null,
  homePointsQ3              smallint not null,
  homePointsQ4              smallint not null,
  homePointsQ5              smallint not null,
  homePointsQ6              smallint not null,
  homePointsQ7              smallint not null,
  homePointsQ8              smallint not null,
  awayTeamAbbr              varchar(3) not null,
  awayConference            varchar(4) not null,
  awayDivision              varchar(9) not null,
  awayResult                varchar(4) not null,
  awayTeamName              varchar(35) not null,
  awayPoints                smallint not null,
  awayAssists               smallint not null,
  awayTurnovers             smallint not null,
  awaySteals                smallint not null,
  awayBlocks                smallint not null,
  awayPersonalFouls         smallint not null,
  awayFieldGoalAttempts     smallint not null,
  awayFieldGoalMade         smallint not null,
  awayThreePointAttempts    smallint not null,
  awayThreePointMade        smallint not null,
  awayFreeThrowAttempts     smallint not null,
  awayFreeThrowMade         smallint not null,
  awayReboundsOffense       smallint not null,
  awayReboundsDefense       smallint not null,
  awayPointsQ1              smallint not null,
  awayPointsQ2              smallint not null,
  awayPointsQ3              smallint not null,
  awayPointsQ4              smallint not null,
  awayPointsQ5              smallint not null,
  awayPointsQ6              smallint not null,
  awayPointsQ7              smallint not null,
  awayPointsQ8              smallint not null,
  constraint ck_official_box_score_seasonType check (seasonType in ('Post','Regular','Pre')),
  constraint ck_official_box_score_homeTeamAbbr check (homeTeamAbbr in ('MIA','NY','DAL','OKC','HOU','DEN','NO','DET','ORL','MIL','CHI','MIN','UTA','LAC','CHA','SAC','IND','BKN','CLE','ATL','WAS','BOS','MEM','POR','GS','LAL','PHO','TOR','PHI','SA')),
  constraint ck_official_box_score_homeConference check (homeConference in ('West','East')),
  constraint ck_official_box_score_homeDivision check (homeDivision in ('Central','Atlantic','Northwest','Pacific','Southeast','Southwest')),
  constraint ck_official_box_score_homeResult check (homeResult in ('Loss','Win')),
  constraint ck_official_box_score_awayTeamAbbr check (awayTeamAbbr in ('MIA','NY','DAL','OKC','HOU','DEN','NO','DET','ORL','MIL','CHI','MIN','UTA','LAC','CHA','SAC','IND','BKN','CLE','ATL','WAS','BOS','MEM','POR','GS','LAL','PHO','TOR','PHI','SA')),
  constraint ck_official_box_score_awayConference check (awayConference in ('West','East')),
  constraint ck_official_box_score_awayDivision check (awayDivision in ('Central','Atlantic','Northwest','Pacific','Southeast','Southwest')),
  constraint ck_official_box_score_awayResult check (awayResult in ('Loss','Win')),
  constraint pk_official_box_score primary key (id))
;

create table player_box_score (
  id                        bigint auto_increment not null,
  gameDate                  datetime not null,
  playerLastName            varchar(25) not null,
  playerFirstName           varchar(25) not null,
  seasonType                varchar(7) not null,
  playerTeamAbbr            varchar(3) not null,
  playerConference          varchar(4) not null,
  playerDivision            varchar(9) not null,
  playerLocation            varchar(4) not null,
  result                    varchar(4) not null,
  fromDate                  date not null,
  toDate                    date not null,
  position                  varchar(5) not null,
  homeTeamName              varchar(35) not null,
  height                    smallint,
  weight                    smallint,
  birthdate                 date,
  birthplace                varchar(50),
  minutes                   smallint,
  starter                   tinyint(1) default 0 not null,
  points                    smallint not null,
  assists                   smallint not null,
  turnovers                 smallint not null,
  steals                    smallint not null,
  blocks                    smallint not null,
  personalFouls             smallint not null,
  fieldGoalAttempts         smallint not null,
  fieldGoalMade             smallint not null,
  threePointAttempts        smallint not null,
  threePointMade            smallint not null,
  freeThrowAttempts         smallint not null,
  freeThrowMade             smallint not null,
  reboundsOffense           smallint not null,
  reboundsDefense           smallint not null,
  pointsQ1                  smallint not null,
  pointsQ2                  smallint not null,
  pointsQ3                  smallint not null,
  pointsQ4                  smallint not null,
  pointsQ5                  smallint not null,
  pointsQ6                  smallint not null,
  pointsQ7                  smallint not null,
  pointsQ8                  smallint not null,
  opponentTeamAbbr          varchar(3) not null,
  opponentConference        varchar(4) not null,
  opponentDivision          varchar(9) not null,
  opponentTeamName          varchar(25) not null,
  official1LastName         varchar(25) not null,
  official1FirstName        varchar(25) not null,
  official2LastName         varchar(25) not null,
  official2FirstName        varchar(35) not null,
  official3LastName         varchar(25) not null,
  official3FirstName        varchar(25) not null,
  constraint ck_player_box_score_seasonType check (seasonType in ('Post','Regular','Pre')),
  constraint ck_player_box_score_playerTeamAbbr check (playerTeamAbbr in ('MIA','NY','DAL','OKC','HOU','DEN','NO','DET','ORL','MIL','CHI','MIN','UTA','LAC','CHA','SAC','IND','BKN','CLE','ATL','WAS','BOS','MEM','POR','GS','LAL','PHO','TOR','PHI','SA')),
  constraint ck_player_box_score_playerConference check (playerConference in ('West','East')),
  constraint ck_player_box_score_playerDivision check (playerDivision in ('Central','Atlantic','Northwest','Pacific','Southeast','Southwest')),
  constraint ck_player_box_score_playerLocation check (playerLocation in ('Away','Home')),
  constraint ck_player_box_score_result check (result in ('Loss','Win')),
  constraint ck_player_box_score_position check (position in ('F','SF','G','SG','C','PF','PG')),
  constraint ck_player_box_score_opponentTeamAbbr check (opponentTeamAbbr in ('MIA','NY','DAL','OKC','HOU','DEN','NO','DET','ORL','MIL','CHI','MIN','UTA','LAC','CHA','SAC','IND','BKN','CLE','ATL','WAS','BOS','MEM','POR','GS','LAL','PHO','TOR','PHI','SA')),
  constraint ck_player_box_score_opponentConference check (opponentConference in ('West','East')),
  constraint ck_player_box_score_opponentDivision check (opponentDivision in ('Central','Atlantic','Northwest','Pacific','Southeast','Southwest')),
  constraint pk_player_box_score primary key (id))
;

create table team_box_score (
  id                        bigint auto_increment not null,
  gameDate                  datetime not null,
  seasonType                varchar(7) not null,
  homeTeamAbbr              varchar(3) not null,
  homeConference            varchar(4) not null,
  homeDivision              varchar(9) not null,
  homeResult                varchar(4) not null,
  homeTeamName              varchar(35) not null,
  homePoints                smallint not null,
  homeAssists               smallint not null,
  homeTurnovers             smallint not null,
  homeSteals                smallint not null,
  homeBlocks                smallint not null,
  homePersonalFouls         smallint not null,
  homeFieldGoalAttempts     smallint not null,
  homeFieldGoalMade         smallint not null,
  homeThreePointAttempts    smallint not null,
  homeThreePointMade        smallint not null,
  homeFreeThrowAttempts     smallint not null,
  homeFreeThrowMade         smallint not null,
  homeReboundsOffense       smallint not null,
  homeReboundsDefense       smallint not null,
  homePointsQ1              smallint not null,
  homePointsQ2              smallint not null,
  homePointsQ3              smallint not null,
  homePointsQ4              smallint not null,
  homePointsQ5              smallint not null,
  homePointsQ6              smallint not null,
  homePointsQ7              smallint not null,
  homePointsQ8              smallint not null,
  awayTeamAbbr              varchar(3) not null,
  awayConference            varchar(4) not null,
  awayDivision              varchar(9) not null,
  awayResult                varchar(4) not null,
  awayTeamName              varchar(35) not null,
  awayPoints                smallint not null,
  awayAssists               smallint not null,
  awayTurnovers             smallint not null,
  awaySteals                smallint not null,
  awayBlocks                smallint not null,
  awayPersonalFouls         smallint not null,
  awayFieldGoalAttempts     smallint not null,
  awayFieldGoalMade         smallint not null,
  awayThreePointAttempts    smallint not null,
  awayThreePointMade        smallint not null,
  awayFreeThrowAttempts     smallint not null,
  awayFreeThrowMade         smallint not null,
  awayReboundsOffense       smallint not null,
  awayReboundsDefense       smallint not null,
  awayPointsQ1              smallint not null,
  awayPointsQ2              smallint not null,
  awayPointsQ3              smallint not null,
  awayPointsQ4              smallint not null,
  awayPointsQ5              smallint not null,
  awayPointsQ6              smallint not null,
  awayPointsQ7              smallint not null,
  awayPointsQ8              smallint not null,
  official1LastName         varchar(25) not null,
  official1FirstName        varchar(25) not null,
  official2LastName         varchar(25) not null,
  official2FirstName        varchar(25) not null,
  official3LastName         varchar(25) not null,
  official3FirstName        varchar(25) not null,
  constraint ck_team_box_score_seasonType check (seasonType in ('Post','Regular','Pre')),
  constraint ck_team_box_score_homeTeamAbbr check (homeTeamAbbr in ('MIA','NY','DAL','OKC','HOU','DEN','NO','DET','ORL','MIL','CHI','MIN','UTA','LAC','CHA','SAC','IND','BKN','CLE','ATL','WAS','BOS','MEM','POR','GS','LAL','PHO','TOR','PHI','SA')),
  constraint ck_team_box_score_homeConference check (homeConference in ('West','East')),
  constraint ck_team_box_score_homeDivision check (homeDivision in ('Central','Atlantic','Northwest','Pacific','Southeast','Southwest')),
  constraint ck_team_box_score_homeResult check (homeResult in ('Loss','Win')),
  constraint ck_team_box_score_awayTeamAbbr check (awayTeamAbbr in ('MIA','NY','DAL','OKC','HOU','DEN','NO','DET','ORL','MIL','CHI','MIN','UTA','LAC','CHA','SAC','IND','BKN','CLE','ATL','WAS','BOS','MEM','POR','GS','LAL','PHO','TOR','PHI','SA')),
  constraint ck_team_box_score_awayConference check (awayConference in ('West','East')),
  constraint ck_team_box_score_awayDivision check (awayDivision in ('Central','Atlantic','Northwest','Pacific','Southeast','Southwest')),
  constraint ck_team_box_score_awayResult check (awayResult in ('Loss','Win')),
  constraint pk_team_box_score primary key (id))
;




# --- !Downs

SET FOREIGN_KEY_CHECKS=0;

drop table official_box_score;

drop table player_box_score;

drop table team_box_score;

SET FOREIGN_KEY_CHECKS=1;

